[project]
name = "triquest-api"
version = "1.0.0"
description = "API REST do jogo educacional TriQuest"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Flask==3.1.1",
    "python-dotenv==1.1.1",
]

[tool.ruff]
line-length = 110
target-version = "py312"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
